# .zshrc-kswchoo.sh
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#  DO NOT EDIT THIS FILE DIRECTLY IN LOCAL FILE SYSTEM.
#  CHANGES WILL BE OVERWRITTEN WHEN YOU REOPENS TERMINAL.
#  PLEASE EDIT FILE SITTING AT DOTFILES_URL BELOW.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DOTFILES_URL="http://awsor.sungwoo.me/private/dotfiles.tar.gz"
DOTFILES_TMP=".dotfiles.tar.gz"

if (($+DOTFILES_DOWNLOADED)); then
echo "Hi, Kevin. It's good time to hack."

################################################################################
## ZSH CONFIGURATIONS

###
### PROMPT

# Prepare short version of hostname
PROMPT_HOSTNAME=$(hostname)
PROMPT_HOSTNAME="${PROMPT_HOSTNAME:s/.ant.amazon.com/}"       # Amazon ANT
PROMPT_HOSTNAME="${PROMPT_HOSTNAME:s/.eu-west-1.amazon.com/}" # Amazon eu-west-1
PROMPT_HOSTNAME="${PROMPT_HOSTNAME:s/.i.sungwoo.me/}"         # KevinNet

# Display git branch info on right
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%b'

# Set prompt variable
autoload colors && colors
export PROMPT="%{$fg[red]%}%n%{$fg[default]%}@%{$fg[cyan]%}$PROMPT_HOSTNAME%{$fg[default]%}:%{$fg[green]%}%~%{$fg[default]%}%# "


###
### KEY BINDINGS

# Fix home/end keys
bindkey "^[^[[D" backward-word      # Alt + ←
bindkey "^[^[[C" forward-word       # Alt + →
bindkey "^[[H" beginning-of-line    # Home
bindkey "^[[F" end-of-line          # End


###
#### ZSH OPTIONS

setopt ALWAYS_TO_END
setopt AUTO_NAME_DIRS
setopt AUTO_PUSHD
setopt NO_BEEP
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
HISTSIZE=16000
SAVEHIST=15000
HISTFILE=~/.history


###
### OS X SPECIFIC

# coreutils
if [[ -a /usr/local/share/info/coreutils.info ]]; then
  alias ls="gls --color"
  alias cp="gcp"
  alias mv="gmv"
  alias ln="gln"
  alias dd="gdd"
  alias df="gdf"
  alias dir="gdir"
  alias who="gwho"
  alias whoami="gwhoami"
fi

# gnu-tar
if [[ -a /usr/local/share/info/tar.info ]]; then
  alias tar="gtar"
fi

################################################################################
## DOTFILE SYNCHRONIZATION STUFFS

else
  echo -n "Updating dotfiles to latestst version... "
  rm -f $DOTFILES_TMP
  wget $DOTFILES_URL -O $DOTFILES_TMP 2&> /dev/null
  if [ -s "$DOTFILES_TMP" ]; then
    tar zxf $DOTFILES_TMP
    rm -f $DOTFILES_TMP
    echo "Done."
  else
    rm -f $DOTFILES_TMP
    echo "Can not download file. Using previous version."
  fi
  export DOTFILES_DOWNLOADED=YES
  source ~/.zshrc-kswchoo.sh
fi

unset DOTFILES_URL
unset DOTFILES_TMP
